"""Additive event-name inventory for the execution_position contract layer."""

CMD_OPEN = "CMD:OPEN"
CMD_CLOSE = "CMD:CLOSE"
CMD_POSITION_POLICY_SIDECAR_CLOSE_REQUEST = (
    "CMD:POSITION_POLICY_SIDECAR_CLOSE_REQUEST"
)

DEC_OPEN = "DEC:OPEN"
DEC_CLOSE = "DEC:CLOSE"
DEC_PLACE_ORDER = "DEC:PLACE_ORDER"
DEC_CANCEL_ORDER = "DEC:CANCEL_ORDER"

EVT_EXECUTION_GUARD_BLOCKED = "EVT:EXECUTION_GUARD_BLOCKED"
EVT_EXECUTION_CLOSE_RECONCILED = "EVT:EXECUTION_CLOSE_RECONCILED"
EVT_ORDER_PLACED = "EVT:ORDER_PLACED"
EVT_ORDER_REJECTED = "EVT:ORDER_REJECTED"
EVT_ORDER_STATE_CHANGED = "EVT:ORDER_STATE_CHANGED"
EVT_POSITION_CLOSED = "EVT:POSITION_CLOSED"
EVT_PENDING_BRACKETS_STORED = "EVT:PENDING_BRACKETS_STORED"
EVT_PENDING_BRACKETS_CLEARED = "EVT:PENDING_BRACKETS_CLEARED"
EVT_BRACKET_PLACEMENT_FAILED = "EVT:BRACKET_PLACEMENT_FAILED"
EVT_POSITION_POLICY_SIDECAR_MODE_ACTIVE = (
    "EVT:POSITION_POLICY_SIDECAR_MODE_ACTIVE"
)
EVT_POSITION_POLICY_SIDECAR_EVALUATED = "EVT:POSITION_POLICY_SIDECAR_EVALUATED"
EVT_POSITION_POLICY_SIDECAR_SCORES = "EVT:POSITION_POLICY_SIDECAR_SCORES"
EVT_POSITION_POLICY_SIDECAR_SUPPRESSED = (
    "EVT:POSITION_POLICY_SIDECAR_SUPPRESSED"
)
EVT_POSITION_POLICY_SIDECAR_RECOMMENDED = (
    "EVT:POSITION_POLICY_SIDECAR_RECOMMENDED"
)
# reserved: schema and registry defined, no runtime emitter — not yet implemented
EVT_POSITION_POLICY_SIDECAR_ACTION_SKIPPED = (
    "EVT:POSITION_POLICY_SIDECAR_ACTION_SKIPPED"
)
EVT_POSITION_POLICY_SIDECAR_CLOSE_REQUEST_STATE = (
    "EVT:POSITION_POLICY_SIDECAR_CLOSE_REQUEST_STATE"
)
EVT_TRADE_EXECUTED = "EVT:TRADE_EXECUTED"

ERR_OPEN = "ERR:OPEN"
ERR_EXECUTION_FAILED = "ERR:EXECUTION_FAILED"
ERR_FATAL_CONFIG_MISMATCH = "ERR:FATAL_CONFIG_MISMATCH"

OWNED_EVENT_NAMES = (
    CMD_OPEN,
    CMD_CLOSE,
    CMD_POSITION_POLICY_SIDECAR_CLOSE_REQUEST,
    DEC_OPEN,
    DEC_CLOSE,
    DEC_PLACE_ORDER,
    DEC_CANCEL_ORDER,
    EVT_EXECUTION_GUARD_BLOCKED,
    EVT_EXECUTION_CLOSE_RECONCILED,
    EVT_ORDER_PLACED,
    EVT_ORDER_REJECTED,
    EVT_ORDER_STATE_CHANGED,
    EVT_POSITION_CLOSED,
    EVT_PENDING_BRACKETS_STORED,
    EVT_PENDING_BRACKETS_CLEARED,
    EVT_BRACKET_PLACEMENT_FAILED,
    EVT_POSITION_POLICY_SIDECAR_MODE_ACTIVE,
    EVT_POSITION_POLICY_SIDECAR_EVALUATED,
    EVT_POSITION_POLICY_SIDECAR_SCORES,
    EVT_POSITION_POLICY_SIDECAR_SUPPRESSED,
    EVT_POSITION_POLICY_SIDECAR_RECOMMENDED,
    EVT_POSITION_POLICY_SIDECAR_ACTION_SKIPPED,
    EVT_POSITION_POLICY_SIDECAR_CLOSE_REQUEST_STATE,
    EVT_TRADE_EXECUTED,
    ERR_OPEN,
    ERR_EXECUTION_FAILED,
    ERR_FATAL_CONFIG_MISMATCH,
)

__all__ = [
    "CMD_CLOSE",
    "CMD_OPEN",
    "CMD_POSITION_POLICY_SIDECAR_CLOSE_REQUEST",
    "DEC_CANCEL_ORDER",
    "DEC_CLOSE",
    "DEC_OPEN",
    "DEC_PLACE_ORDER",
    "ERR_EXECUTION_FAILED",
    "ERR_FATAL_CONFIG_MISMATCH",
    "ERR_OPEN",
    "EVT_BRACKET_PLACEMENT_FAILED",
    "EVT_EXECUTION_CLOSE_RECONCILED",
    "EVT_EXECUTION_GUARD_BLOCKED",
    "EVT_ORDER_PLACED",
    "EVT_ORDER_REJECTED",
    "EVT_ORDER_STATE_CHANGED",
    "EVT_PENDING_BRACKETS_CLEARED",
    "EVT_PENDING_BRACKETS_STORED",
    "EVT_POSITION_CLOSED",
    "EVT_POSITION_POLICY_SIDECAR_ACTION_SKIPPED",
    "EVT_POSITION_POLICY_SIDECAR_CLOSE_REQUEST_STATE",
    "EVT_POSITION_POLICY_SIDECAR_EVALUATED",
    "EVT_POSITION_POLICY_SIDECAR_MODE_ACTIVE",
    "EVT_POSITION_POLICY_SIDECAR_RECOMMENDED",
    "EVT_POSITION_POLICY_SIDECAR_SCORES",
    "EVT_POSITION_POLICY_SIDECAR_SUPPRESSED",
    "EVT_TRADE_EXECUTED",
    "OWNED_EVENT_NAMES",
]
