# apps/reference/domains/execution_position/utils.py
from __future__ import annotations
from decimal import Decimal, ROUND_DOWN, ROUND_UP
from typing import Optional, Tuple, Any, Dict
import hashlib
import re
import math
# DET-BT-11: Use get_clock() for deterministic backtest
from apps.reference.core.time import get_clock

__all__ = [
    "quantize_stop_price",
    "validate_anti_2021",
    "generate_client_order_id",
    "calc_tp_sl_from_mark",
    "validate_not_immediate",
    "opposite_side",
    "BoundedEventDeduper",
    # PREFIX-CANON-01: Canonical prefix registry
    "OrderRolePrefix",
    "classify_client_order_id",
    "is_guardian_managed_prefix",
    "is_bracket_prefix",
    "is_exit_prefix",
    "ALL_KNOWN_PREFIXES",
    "GUARDIAN_MANAGED_PREFIXES",
    # BOOL-COERCE-02: Canonical exchange bool coercion
    "coerce_exchange_bool",
]

# ---- PREFIX-CANON-01: Canonical prefix registry (SSOT) ----
#
# Every clientOrderId generated by execution_position starts with one of
# these prefixes followed by a hyphen.  ALL consumers that classify orders
# by prefix MUST import from this registry — no local hardcoded tuples.
#
# Adding a new prefix?
#   1. Add an entry to OrderRolePrefix below.
#   2. Set its flags (is_bracket, is_exit, guardian_managed).
#   3. The drift-guard test will verify every generate_client_order_id()
#      call site uses a registered prefix.


class OrderRolePrefix:
    """Canonical role definition for a clientOrderId prefix."""

    __slots__ = ("prefix", "role", "is_bracket", "is_exit", "guardian_managed")

    def __init__(
        self,
        prefix: str,
        role: str,
        *,
        is_bracket: bool = False,
        is_exit: bool = False,
        guardian_managed: bool = True,
    ) -> None:
        self.prefix = prefix          # e.g. "SL"
        self.role = role              # canonical role label, e.g. "SL"
        self.is_bracket = is_bracket  # SL/TP/TP1/TP2/BHSL/BHTP
        self.is_exit = is_exit        # any order that reduces/closes position
        self.guardian_managed = guardian_managed


# Canonical registry — single source of truth.
_PREFIX_REGISTRY: tuple[OrderRolePrefix, ...] = (
    OrderRolePrefix("ENTRY",  "ENTRY",  is_bracket=False,
                    is_exit=False, guardian_managed=True),
    OrderRolePrefix("SL",     "SL",     is_bracket=True,
                    is_exit=True,  guardian_managed=True),
    OrderRolePrefix("TP",     "TP",     is_bracket=True,
                    is_exit=True,  guardian_managed=True),
    OrderRolePrefix("TP1",    "TP1",    is_bracket=True,
                    is_exit=True,  guardian_managed=True),
    OrderRolePrefix("TP2",    "TP2",    is_bracket=True,
                    is_exit=True,  guardian_managed=True),
    OrderRolePrefix("BHSL",   "BHSL",   is_bracket=True,
                    is_exit=True,  guardian_managed=True),
    OrderRolePrefix("BHTP",   "BHTP",   is_bracket=True,
                    is_exit=True,  guardian_managed=True),
    OrderRolePrefix("CLOSE",  "CLOSE",  is_bracket=False,
                    is_exit=True,  guardian_managed=True),
)

# Derived constants — frozen at import time.
ALL_KNOWN_PREFIXES: frozenset[str] = frozenset(
    p.prefix for p in _PREFIX_REGISTRY)

GUARDIAN_MANAGED_PREFIXES: tuple[str, ...] = tuple(
    f"{p.prefix}-" for p in _PREFIX_REGISTRY if p.guardian_managed
)

_BRACKET_PREFIXES: frozenset[str] = frozenset(
    p.prefix for p in _PREFIX_REGISTRY if p.is_bracket
)

_EXIT_PREFIXES: frozenset[str] = frozenset(
    p.prefix for p in _PREFIX_REGISTRY if p.is_exit
)

# Matching order: longest prefix first so "TP1-" matches before "TP-".
_SORTED_PREFIX_DASH: tuple[str, ...] = tuple(
    sorted((f"{p.prefix}-" for p in _PREFIX_REGISTRY), key=len, reverse=True)
)

_PREFIX_TO_ROLE: dict[str, str] = {p.prefix: p.role for p in _PREFIX_REGISTRY}


def classify_client_order_id(client_order_id: Optional[str]) -> str:
    """
    Return the canonical role for a clientOrderId, or ``"UNKNOWN"`` if the
    prefix is not recognised.

    Matching is case-insensitive and longest-prefix-first so that ``TP1-``
    is matched before ``TP-``.
    """
    if not client_order_id:
        return "UNKNOWN"
    cid = str(client_order_id).upper()
    for prefix_dash in _SORTED_PREFIX_DASH:
        if cid.startswith(prefix_dash):
            return _PREFIX_TO_ROLE[prefix_dash[:-1]]  # remove trailing "-"
    return "UNKNOWN"


def is_guardian_managed_prefix(client_order_id: Optional[str]) -> bool:
    """Return True if the clientOrderId belongs to a guardian-managed role."""
    if not client_order_id:
        return False
    cid = str(client_order_id).upper()
    return cid.startswith(GUARDIAN_MANAGED_PREFIXES)


def is_bracket_prefix(client_order_id: Optional[str]) -> bool:
    """Return True if the clientOrderId is a bracket order (SL/TP/TP1/TP2/BHSL/BHTP)."""
    role = classify_client_order_id(client_order_id)
    return role in _BRACKET_PREFIXES


def is_exit_prefix(client_order_id: Optional[str]) -> bool:
    """Return True if the clientOrderId represents an exit/reduce order."""
    role = classify_client_order_id(client_order_id)
    return role in _EXIT_PREFIXES


# ---- BOOL-COERCE-02: Canonical exchange bool coercion (SSOT) ----
#
# Binance REST and WS payloads encode reduceOnly / closePosition as either
# a native bool (True/False) or a string ("true"/"false").  This helper
# provides a single deterministic coercion point so that every consumer
# handles these fields identically.
#
# Contract:
#   bool  → returned as-is
#   str   → case-insensitive "true" → True, everything else → False
#   None  → False
#   other → bool(value)  (int 1 → True, 0 → False, etc.)
#
# This is the ONLY correct coercion for exchange order-flag fields.
# Do NOT extend the truthy vocabulary ("yes", "1", etc.) without explicit
# justification and tests — Binance only emits bool or "true"/"false".


def coerce_exchange_bool(value: Any) -> bool:
    """Coerce a Binance exchange bool-like field to a Python bool.

    Handles the two forms Binance emits:
    - Native ``bool``: returned as-is.
    - ``str``: ``"true"`` (case-insensitive) → ``True``, else ``False``.
    - ``None``: → ``False``.
    - Other (int, etc.): ``bool(value)``.
    """
    if isinstance(value, bool):
        return value
    if value is None:
        return False
    if isinstance(value, str):
        return value.strip().lower() == "true"
    return bool(value)


# ---- price quantization helpers ----


def _round_to_tick(
    price: float | Decimal, tick_size: float | Decimal, mode: str = "floor"
) -> float:
    p = Decimal(str(price))
    t = Decimal(str(tick_size))
    if t <= 0:
        return float(p)
    if mode == "floor":
        q = (p / t).to_integral_value(rounding=ROUND_DOWN)
    elif mode == "ceil":
        q = (p / t).to_integral_value(rounding=ROUND_UP)
    else:
        # Binance зазвичай приймає floor; "nearest" не використовуємо для стопів
        q = (p / t).to_integral_value(rounding=ROUND_DOWN)
    return float(q * t)


def quantize_stop_price(
    stop_price: float, tick_size: float, *, side: Optional[str] = None
) -> float:
    """
    Quantize stopPrice to tick_size multiples.

    FIXED LOGIC:
    - side="BUY" (SL for Short, Price > Market): Round UP (CEIL) to avoid premature trigger.
    - side="SELL" (SL for Long, Price < Market): Round DOWN (FLOOR) to avoid premature trigger.
    - side=None: Defaults to legacy behavior (FLOOR), but logs warning if debug enabled.
    """
    if side:
        s = side.upper()
        if s == "BUY":
            return _round_to_tick(stop_price, tick_size, mode="ceil")
        elif s == "SELL":
            return _round_to_tick(stop_price, tick_size, mode="floor")

    # Fallback / Default behavior (now safe-guarded by explicit side logic above)
    return _round_to_tick(stop_price, tick_size, mode="floor")


# ---- anti-2021 guard ----


def validate_anti_2021(
    side: str,
    order_type: str,
    stop_price: float,
    trigger_price: float,
    tick_size: float,
) -> Tuple[float, bool, str]:
    """
    Перевіряє та (за потреби) зсуває stop_price на правильний бік відносно trigger_price,
    щоб уникнути Binance -2021 ("Order would immediately trigger").

    Повертає: (коригований_stop_price, чи_було_змінено, причина)
    """
    s = (side or "").upper()
    t = (order_type or "").upper()
    adjusted = False
    reason_parts: list[str] = []

    # 1 тик або мінімальний мікро-зсув
    eps = max(float(tick_size), float(trigger_price) * 1e-9)

    def nudge_down(px: float) -> float:
        return px - eps

    def nudge_up(px: float) -> float:
        return px + eps

    if t in {"STOP", "STOP_MARKET", "TAKE_PROFIT", "TAKE_PROFIT_MARKET"}:
        if s == "SELL":
            if t.startswith("STOP"):
                # SL для LONG: має бути СТРОГО < trigger
                if not (stop_price < trigger_price):
                    stop_price = nudge_down(trigger_price)
                    adjusted = True
                    reason_parts.append("sell STOP must be < trigger")
            else:
                # TP для LONG: має бути СТРОГО > trigger
                if not (stop_price > trigger_price):
                    stop_price = nudge_up(trigger_price)
                    adjusted = True
                    reason_parts.append("sell TP must be > trigger")
        elif s == "BUY":
            if t.startswith("STOP"):
                # SL для SHORT: має бути СТРОГО > trigger
                if not (stop_price > trigger_price):
                    stop_price = nudge_up(trigger_price)
                    adjusted = True
                    reason_parts.append("buy STOP must be > trigger")
            else:
                # TP для SHORT: має бути СТРОГО < trigger
                if not (stop_price < trigger_price):
                    stop_price = nudge_down(trigger_price)
                    adjusted = True
                    reason_parts.append("buy TP must be < trigger")

    # Квантуємо з урахуванням напряму
    sp_q = quantize_stop_price(stop_price, tick_size, side=s)

    # Якщо після округлення дорівнює тригеру — зсунь ще на 1 тик
    if abs(sp_q - trigger_price) < 1e-15:
        if (s == "SELL" and t.startswith("STOP")) or (
            s == "BUY" and t.startswith("TAKE_PROFIT")
        ):
            sp_q -= float(tick_size)
        else:
            sp_q += float(tick_size)
        adjusted = True
        reason_parts.append("nudge one tick away from trigger")

    return float(sp_q), adjusted, "; ".join(reason_parts)


# ---- clientOrderId helper (<=36 chars) ----


def generate_client_order_id(
    prefix: str,
    decision_id: str,
    extra: str | None = None,
    *,
    idempotent_key: str | None = None,
    max_len: int = 32,
    config: Optional[Any] = None,
) -> str:
    """
    Створює короткий детермінований clientOrderId (Binance: <36 симв.).
    """
    # Try to get max_len from domains config if provided
    if config:
        try:
            if hasattr(config, 'domains') and hasattr(config.domains, 'execution_position'):
                max_len = config.domains.execution_position.utils.client_order_id_max_length
        except (AttributeError, TypeError):
            pass  # Use provided/default value

    role_set = {"ENTRY", "SL", "TP", "CLOSE"}

    # Deterministic mode:
    # - If idempotent_key is explicitly provided, derive a stable clientOrderId from it.
    # - Also support stable IDs for legacy callers that pass (role, rid, extra=symbol).
    if idempotent_key is not None:
        role = str(prefix)
        symbol = str(decision_id)
        raw_str = f"{idempotent_key}|{role}|{symbol}"
        hash_part = hashlib.md5(raw_str.encode("utf-8")).hexdigest()[:12]
        cid = f"{role}-{hash_part}"
    elif extra is not None and str(prefix).upper() in role_set:
        role = str(prefix).upper()
        stable_key = str(decision_id)
        symbol = str(extra)
        raw_str = f"{stable_key}|{role}|{symbol}"
        hash_part = hashlib.md5(raw_str.encode("utf-8")).hexdigest()[:12]
        cid = f"{role}-{hash_part}"
    else:
        # DET-BT-11: Use get_clock() for deterministic backtest
        base = f"{prefix}:{decision_id}:{extra or ''}:{get_clock().now_ms()}"
        h = hashlib.sha1(base.encode("utf-8")).hexdigest()[:10]
        cid = f"{prefix}-{h}"

    if len(cid) > max_len:
        cid = cid[:max_len]
    # тільки дозволені символи
    return re.sub(r"[^A-Za-z0-9_\-]", "", cid)


# ---- additional utilities ----


def _to_float(val: Any, *, name: str = "value") -> float:
    """
    Robustly convert mark-like value to float. Accepts dict/str/Decimal/float/int.
    If dict is provided, looks for common keys.
    """
    if val is None:
        raise ValueError(f"{name} is None")
    if isinstance(val, (int, float)):
        return float(val)
    if isinstance(val, Decimal):
        return float(val)
    if isinstance(val, str):
        return float(val)
    if isinstance(val, dict):
        for k in ("markPrice", "price", "last", "lastPrice", "indexPrice"):
            v = val.get(k)
            if v is not None:
                return float(v)
    raise TypeError(f"Expected number-like for {name}, got {type(val)}: {val}")


def calc_tp_sl_from_mark(
    mark: Any,
    side: str,
    tp_bps: Any,
    sl_bps: Any,
    tick_size: Optional[float] = None,
    config: Optional[Any] = None,
) -> tuple[float, float]:
    """
    Розрахунок TP/SL від MARK_PRICE.
    Приймає mark як dict/str/float/Decimal. tp_bps/sl_bps можуть бути стрічками або числами.

    Args:
        mark: mark price або словник з ключем 'markPrice'/'price'/'last'.
        side: 'LONG' або 'SHORT'
        tp_bps: take-profit в б.п. (100 б.п. = 1%)
        sl_bps: stop-loss в б.п.
        tick_size: опційно — крок квантування ціни.
        config: опційно — configuration object

    Returns:
        (tp_price, sl_price)
    """
    m = _to_float(mark, name="mark")

    # Try to get basis_points_base from domains config
    b = 10000.0  # default
    if config:
        try:
            if hasattr(config, 'domains') and hasattr(config.domains, 'execution_position'):
                b = config.domains.execution_position.utils.basis_points_base
        except (AttributeError, TypeError):
            pass  # Use default

    tp_bps_f = _to_float(tp_bps, name="tp_bps")
    sl_bps_f = _to_float(sl_bps, name="sl_bps")

    s = (side or "").upper()
    if s == "LONG":
        tp = m * (1.0 + tp_bps_f / b)
        sl = m * (1.0 - sl_bps_f / b)
        # kвантування: TP ↑, SL ↓
        if tick_size and tick_size > 0:
            tp = _round_to_tick(tp, tick_size, mode="ceil")
            sl = _round_to_tick(sl, tick_size, mode="floor")
        # анти-2021
        if not (sl < m and tp > m):
            raise ValueError(
                f"anti-2021 (LONG) failed: sl={sl}, tp={tp}, mark={m}")
    elif s == "SHORT":
        tp = m * (1.0 - tp_bps_f / b)
        sl = m * (1.0 + sl_bps_f / b)
        if tick_size and tick_size > 0:
            tp = _round_to_tick(tp, tick_size, mode="floor")
            sl = _round_to_tick(sl, tick_size, mode="ceil")
        if not (sl > m and tp < m):
            raise ValueError(
                f"anti-2021 (SHORT) failed: sl={sl}, tp={tp}, mark={m}")
    else:
        raise ValueError("Side must be 'LONG' or 'SHORT'")

    return float(tp), float(sl)


def validate_not_immediate(side: str, tp, sl, mark) -> float:
    """
    Анти-2021 перевірка: тригер не має спрацювати одразу.
    Повертає нормалізований mark (float) для подальшого логування.
    """
    m = _to_float(mark, name="mark")
    tp_f = _to_float(tp, name="tp")
    sl_f = _to_float(sl, name="sl")

    s = (side or "").upper()
    if s == "LONG":
        # LONG: SL < mark, TP > mark
        if sl_f >= m:
            raise ValueError(
                f"anti-2021 (LONG) failed: SL({sl_f}) >= mark({m})")
        if tp_f <= m:
            raise ValueError(
                f"anti-2021 (LONG) failed: TP({tp_f}) <= mark({m})")
    elif s == "SHORT":
        # SHORT: SL > mark, TP < mark
        if sl_f <= m:
            raise ValueError(
                f"anti-2021 (SHORT) failed: SL({sl_f}) <= mark({m})")
        if tp_f >= m:
            raise ValueError(
                f"anti-2021 (SHORT) failed: TP({tp_f}) >= mark({m})")
    else:
        raise ValueError(f"Unknown side: {side}")

    return m


def opposite_side(side: str) -> str:
    """
    Get opposite side.

    Args:
        side: 'BUY' or 'SELL'.

    Returns:
        Opposite side.
    """
    return "SELL" if side == "BUY" else "BUY"


class BoundedEventDeduper(set):
    """
    Bounded idempotency tracker with TTL and MaxSize.
    Inherits from set to maintain compatibility with existing tests and FSM logic.
    """

    def __init__(self, max_size: int = 100000, ttl_ms: int = 86400000):
        super().__init__()
        from collections import OrderedDict
        self.max_size = max_size
        self.ttl_ms = ttl_ms
        self._ts: OrderedDict[str, int] = OrderedDict()

    def seen(self, event_key: str) -> bool:
        """Check if event was already processed."""
        return event_key in self

    def add(self, event_key: str, now_ms: int | None = None):
        """Mark event as processed and prune old entries."""
        if now_ms is None:
            # DET-BT-11: Use get_clock() for deterministic backtest
            now_ms = get_clock().now_ms()

        super().add(event_key)
        if event_key in self._ts:
            self._ts.move_to_end(event_key)
        self._ts[event_key] = now_ms
        self.prune(now_ms)

    def prune(self, now_ms: int):
        """Evict by TTL and then by MaxSize."""
        # 1. TTL Prune (Oldest first)
        while self._ts:
            first_key = next(iter(self._ts))
            first_ts = self._ts[first_key]
            if now_ms - first_ts > self.ttl_ms:
                self._ts.popitem(last=False)
                if first_key in self:
                    super().remove(first_key)
            else:
                break

        # 2. Size Prune
        while len(self._ts) > self.max_size:
            evict_key, _ = self._ts.popitem(last=False)
            if evict_key in self:
                super().remove(evict_key)

def resolve_price(pld: Dict[str, Any], key: str) -> Optional[str]:
    """
    Smart extraction to handle flat (DecisionMaking) vs nested (Strategy) payloads.

    Priority:
    1. Root level (normalized by DM)
    2. price_ctx (raw strategy output, e.g., MeanReversion)
    3. order nested object (legacy/alternative structure)

    CFG-SMART-EXTRACT-01: Ensures stop_price/target_price are found regardless
    of where Strategy places them in the payload hierarchy.
    """
    # 1. Root level
    val = pld.get(key)
    if val not in (None, "", "None", "null"):
        return str(val)

    # 2. Nested price_ctx (e.g., from MeanReversion strategy)
    price_ctx = pld.get("price_ctx")
    if isinstance(price_ctx, dict):
        ctx_val = price_ctx.get(key)
        if ctx_val not in (None, "", "None", "null"):
            return str(ctx_val)

    # 3. Nested order object (alternative/legacy structure)
    order = pld.get("order")
    if isinstance(order, dict):
        order_val = order.get(key)
        if order_val not in (None, "", "None", "null"):
            return str(order_val)

    return None

