[tool:pytest]
testpaths = tests
norecursedirs = scripts docs htmlcov tmp_test_* *.tmp
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
addopts = -ra -q
asyncio_mode = strict
markers =
    integration: marks tests as integration tests
    ws_rest: marks tests as websocket/rest tests
    scen: marks tests as scenario tests