"""
Tests for BATCH message handling in ExecPosFSM.

This test suite verifies:
1. BATCH message unpacking
2. Bracket ID synchronization after PLACE_ORDER execution
3. OCO emulation works correctly with BATCH-placed brackets
"""

import pytest
import asyncio
from unittest.mock import Mock, AsyncMock, MagicMock
from decimal import Decimal

from vfoundation.core.protocol import Message


class TestBatchHandling:
    """Test BATCH message processing in ExecPosFSM"""
    
    @pytest.fixture
    def mock_fsm(self):
        """Create a mock ExecPosFSM with necessary attributes"""
        fsm = Mock()
        fsm.shadow_mode = False
        fsm.adapter = AsyncMock()
        fsm.manage_flows = {}
        fsm._symbol_brackets = {}
        fsm._get_async_loop = Mock(return_value=asyncio.get_event_loop())
        fsm._submit_async = Mock()
        return fsm
    
    @pytest.fixture
    def mock_manage_flow(self):
        """Create a mock ManageFlowFSM"""
        manage = Mock()
        manage.set_bracket_ids = Mock()
        return manage
    
    def test_batch_unpacking(self, mock_fsm):
        """Test that BATCH messages are correctly unpacked"""
        # Create BATCH message with SL and TP orders
        sl_order = Message(
            op="DEC",
            verb="PLACE_ORDER",
            src="execution_position",
            dst="execution_position",
            rid="test_rid",
            pld={
                "symbol": "BTCUSDT",
                "side": "SELL",
                "qty": "0.001",
                "order_type": "STOP_MARKET",
                "stopPrice": "99500",
                "newClientOrderId": "test_rid_1234567890_sl"
            }
        )
        
        tp_order = Message(
            op="DEC",
            verb="PLACE_ORDER",
            src="execution_position",
            dst="execution_position",
            rid="test_rid",
            pld={
                "symbol": "BTCUSDT",
                "side": "SELL",
                "qty": "0.001",
                "order_type": "TAKE_PROFIT_MARKET",
                "stopPrice": "100500",
                "newClientOrderId": "test_rid_1234567890_tp"
            }
        )
        
        batch_msg = Message(
            op="DEC",
            verb="BATCH",
            src="execution_position",
            dst="execution_position",
            rid="test_rid",
            pld={
                "messages": [sl_order.model_dump(), tp_order.model_dump()]
            }
        )
        
        # Verify BATCH structure
        assert batch_msg.verb == "BATCH"
        assert "messages" in batch_msg.pld
        messages = batch_msg.pld["messages"]
        assert len(messages) == 2
        
        # Verify SL order
        assert messages[0]["verb"] == "PLACE_ORDER"
        assert messages[0]["pld"]["order_type"] == "STOP_MARKET"
        assert "_sl" in messages[0]["pld"]["newClientOrderId"]
        
        # Verify TP order
        assert messages[1]["verb"] == "PLACE_ORDER"
        assert messages[1]["pld"]["order_type"] == "TAKE_PROFIT_MARKET"
        assert "_tp" in messages[1]["pld"]["newClientOrderId"]
    
    def test_tp_order_type_is_take_profit_market(self):
        """
        CRITICAL: Verify TP order uses TAKE_PROFIT_MARKET not LIMIT
        
        This is Bug #1 fix verification.
        """
        # This would be generated by ManageFlowFSM._place_brackets()
        tp_pld = {
            "symbol": "BTCUSDT",
            "order_type": "TAKE_PROFIT_MARKET",  # NOT "LIMIT"!
            "stopPrice": "100500",
        }
        
        assert tp_pld["order_type"] == "TAKE_PROFIT_MARKET", \
            "TP must use TAKE_PROFIT_MARKET type, not LIMIT"
    
    @pytest.mark.asyncio
    async def test_bracket_id_sync_after_place_order(self, mock_fsm, mock_manage_flow):
        """
        Test bracket ID synchronization with ManageFlowFSM.
        
        This is Bug #2 fix verification.
        """
        symbol = "BTCUSDT"
        mock_fsm.manage_flows[symbol] = mock_manage_flow
        
        # Simulate adapter responses
        sl_resp = {"orderId": "SL_ORDER_123"}
        tp_resp = {"orderId": "TP_ORDER_456"}
        
        # Simulate PLACE_ORDER execution for SL
        client_id_sl = "test_rid_1234567890_sl"
        mock_fsm._symbol_brackets[symbol] = {}
        mock_fsm._symbol_brackets[symbol]["sl_order_id"] = str(sl_resp["orderId"])
        
        # Simulate PLACE_ORDER execution for TP
        client_id_tp = "test_rid_1234567890_tp"
        mock_fsm._symbol_brackets[symbol]["tp_order_id"] = str(tp_resp["orderId"])
        
        # This is the critical fix: sync IDs with ManageFlowFSM
        current_sl = mock_fsm._symbol_brackets.get(symbol, {}).get("sl_order_id")
        current_tp = mock_fsm._symbol_brackets.get(symbol, {}).get("tp_order_id")
        mock_manage_flow.set_bracket_ids(current_sl, current_tp)
        
        # Verify set_bracket_ids was called with correct IDs
        mock_manage_flow.set_bracket_ids.assert_called_once_with("SL_ORDER_123", "TP_ORDER_456")
    
    def test_batch_order_types(self):
        """Verify correct order types for SL and TP in BATCH"""
        sl_type = "STOP_MARKET"
        tp_type = "TAKE_PROFIT_MARKET"
        
        # SL should be STOP_MARKET
        assert sl_type == "STOP_MARKET", "SL must use STOP_MARKET type"
        
        # TP should be TAKE_PROFIT_MARKET (NOT LIMIT)
        assert tp_type == "TAKE_PROFIT_MARKET", "TP must use TAKE_PROFIT_MARKET type"
        assert tp_type != "LIMIT", "TP must NOT use LIMIT type"


class TestBatchOCOIntegration:
    """Test OCO emulation works correctly with BATCH-placed brackets"""
    
    @pytest.fixture
    def mock_manage_fsm_with_batch_brackets(self):
        """Create ManageFlowFSM with brackets placed via BATCH"""
        # Import dynamically
        import importlib.util
        import os
        
        spec = importlib.util.spec_from_file_location(
            "fsm_manage",
            os.path.join(
                os.path.dirname(__file__),
                "..",
                "..",
                "apps",
                "reference",
                "domains",
                "execution_position",
                "fsm_manage.py",
            ),
        )
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        ManageFlowFSM = mod.ManageFlowFSM
        
        fsm = ManageFlowFSM(config={
            "trading": {
                "execution": {
                    "manage": {
                        "brackets": {
                            "oco_emulation": True,
                            "enable": True,
                        }
                    }
                }
            }
        })
        
        # Simulate position with brackets placed via BATCH
        fsm.position_qty = Decimal("0.001")
        fsm.position_entry_price = Decimal("100000")
        fsm.position_side = "BUY"
        fsm.sl_order_id = "SL_ORDER_123"  # Set via BATCH → set_bracket_ids()
        fsm.tp_order_id = "TP_ORDER_456"  # Set via BATCH → set_bracket_ids()
        
        return fsm
    
    def test_batch_placed_tp_fill_cancels_sl(self, mock_manage_fsm_with_batch_brackets):
        """
        Test OCO works with BATCH-placed brackets: TP fills → SL cancelled
        """
        fsm = mock_manage_fsm_with_batch_brackets
        
        # TP fills
        tp_fill_msg = Message(
            op="EVT",
            verb="TRADE_EXECUTED",
            src="test",
            dst="manage",
            rid="test",
            pld={
                "symbol": "BTCUSDT",
                "orderId": "TP_ORDER_456",
                "price": "100500",
            }
        )
        
        result = fsm._handle_bracket_fill(tp_fill_msg)
        
        # OCO should emit CANCEL for SL
        assert result is not None, "OCO should emit cancel decision"
        assert result.verb == "CANCEL_ORDER", "Should cancel SL order"
        assert result.pld.get("orderId") == "SL_ORDER_123", "Should cancel correct SL order"
        
        # TP ID should be cleared
        assert fsm.tp_order_id is None, "TP order cleared after fill"
    
    def test_batch_placed_sl_fill_cancels_tp(self, mock_manage_fsm_with_batch_brackets):
        """
        Test OCO works with BATCH-placed brackets: SL fills → TP cancelled
        """
        fsm = mock_manage_fsm_with_batch_brackets
        
        # SL fills
        sl_fill_msg = Message(
            op="EVT",
            verb="TRADE_EXECUTED",
            src="test",
            dst="manage",
            rid="test",
            pld={
                "symbol": "BTCUSDT",
                "orderId": "SL_ORDER_123",
                "price": "99500",
            }
        )
        
        result = fsm._handle_bracket_fill(sl_fill_msg)
        
        # OCO should emit CANCEL for TP
        assert result is not None, "OCO should emit cancel decision"
        assert result.verb == "CANCEL_ORDER", "Should cancel TP order"
        assert result.pld.get("orderId") == "TP_ORDER_456", "Should cancel correct TP order"
        
        # SL ID should be cleared
        assert fsm.sl_order_id is None, "SL order cleared after fill"


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
